name: lmw
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  lottie: ^3.1.3
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^18.0.1
  flutter_rating_bar: ^4.0.1
  qr_code_scanner: ^1.0.1
  flutter_screenutil: ^5.9.3
#  qr_code_scanner: ^1.0.1
#  geolocator: ^11.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/luncher.png"
  flutter_lints: ^2.0.0
flutter:
  generate: true
  assets:
    - assets/animation/
    - assets/images/
  uses-material-design: true